import 'package:easy_localization/easy_localization.dart';

Map<String, String> koreanBankIcon = {
  // "교보": "asset/img/bank/금융아이콘_PNG_교보.png",
  // "CHUBB": "asset/img/bank/금융아이콘_PNG_CHUBB.png",
  "BNK": "asset/img/bank/금융아이콘_PNG_BNK.png",
  "bank name.citi".tr(): "asset/img/bank/금융아이콘_PNG_씨티.png",
  "KDB": "asset/img/bank/금융아이콘_PNG_KDB.png",
  // "부국증권": "asset/img/bank/금융아이콘_PNG_부국증권.png",
  // "푸본현대생명": "asset/img/bank/금융아이콘_PNG_푸본현대생명.png",
  // "한국투자": "asset/img/bank/금융아이콘_PNG_한국투자.png",
  "bank name.hanhwa".tr(): "asset/img/bank/금융아이콘_PNG_한화.png",
  // "신협": "asset/img/bank/금융아이콘_PNG_신협.png",
  "bank name.mirae asset".tr(): "asset/img/bank/금융아이콘_PNG_미래에셋.png",
  // "코리아리재": "asset/img/bank/금융아이콘_PNG_코리아리재.png",
  // "우체국": "asset/img/bank/금융아이콘_PNG_우체국.png",
  "bank name.kakao".tr(): "asset/img/bank/금융아이콘_PNG_카카오뱅크.png",
  // "중국공상은행": "asset/img/bank/금융아이콘_PNG_중국공상은행.png",
  // "메리츠": "asset/img/bank/금융아이콘_PNG_메리츠.png",
  // "라이나생명": "asset/img/bank/금융아이콘_PNG_라이나생명.png",
  "bank name.shinhan".tr(): "asset/img/bank/금융아이콘_PNG_신한.png",
  // "저축은행": "asset/img/bank/금융아이콘_PNG_저축은행.png",
  // "BOA은행": "asset/img/bank/금융아이콘_PNG_BOA은행.png",
  // "유안타": "asset/img/bank/금융아이콘_PNG_유안타.png",
  // "산림조합": "asset/img/bank/금융아이콘_PNG_산림조합.png",
  // "JP모건체이스": "asset/img/bank/금융아이콘_PNG_JP모건체이스.png",
  // "한국포스": "asset/img/bank/금융아이콘_PNG_한국포스.png",
  // "교보라이프플래닛": "asset/img/bank/금융아이콘_PNG_교보라이프플래닛.png",
  // "중국은행": "asset/img/bank/금융아이콘_PNG_중국은행.png",
  // "BNP파리바": "asset/img/bank/금융아이콘_PNG_BNP파리바.png",
  // "Sh수협": "asset/img/bank/금융아이콘_PNG_Sh수협.png",
  "DGB": "asset/img/bank/금융아이콘_PNG_DGB.png",
  // "이베스트": "asset/img/bank/금융아이콘_PNG_이베스트.png",
  // "푸르덴셜": "asset/img/bank/금융아이콘_PNG_푸르덴셜.png",
  // "MG새마을금고": "asset/img/bank/금융아이콘_PNG_MG새마을금고.png",
  "KB": "asset/img/bank/금융아이콘_PNG_KB.png",
  // "AXA": "asset/img/bank/금융아이콘_PNG_AXA.png",
  "bank name.shinhan".tr(): "asset/img/bank/금융아이콘_PNG_신한카드.png",
  "bank name.toss".tr(): "asset/img/bank/금융아이콘_PNG_토스.png",
  "BC": "asset/img/bank/금융아이콘_PNG_BC카드.png",
  // "ABL": "asset/img/bank/금융아이콘_PNG_ABL.png",
  // "메트라이프": "asset/img/bank/금융아이콘_PNG_메트라이프.png",
  "SK": "asset/img/bank/금융아이콘_PNG_SK.png",
  "bank name.samsung".tr(): "asset/img/bank/금융아이콘_PNG_삼성.png",
  // "DB": "asset/img/bank/금융아이콘_PNG_DB.png",
  "bank name.nh".tr(): "asset/img/bank/금융아이콘_PNG_농협.png",
  "bank name.hyundai".tr(): "asset/img/bank/금융아이콘_PNG_현대카드.png",
  // "도이치뱅크": "asset/img/bank/금융아이콘_PNG_도이치뱅크.png",
  "bank name.kbank".tr(): "asset/img/bank/금융아이콘_PNG_케이뱅크.png",
  // "키움": "asset/img/bank/금융아이콘_PNG_키움.png",
  "IBK": "asset/img/bank/금융아이콘_PNG_IBK.png",
  "bank name.lotte".tr(): "asset/img/bank/금융아이콘_PNG_롯데.png",
  // "현대해상": "asset/img/bank/금융아이콘_PNG_현대해상.png",
  "bank name.woori".tr(): "asset/img/bank/금융아이콘_PNG_우리.png",
  // "대신증권": "asset/img/bank/금융아이콘_PNG_대신증권.png",
  // "SC제일": "asset/img/bank/금융아이콘_PNG_SC제일.png",
  // "중국건설은행": "asset/img/bank/금융아이콘_PNG_중국건설은행.png",
  // "신영증권": "asset/img/bank/금융아이콘_PNG_신영증권.png",
  // "흥국": "asset/img/bank/금융아이콘_PNG_흥국.png",
  // "HSBC": "asset/img/bank/금융아이콘_PNG_HSBC.png",
  // "광주": "asset/img/bank/금융아이콘_PNG_광주.png",
  "bank name.hana".tr(): "asset/img/bank/금융아이콘_PNG_하나.png",
  // "수호천사동양생명": "asset/img/bank/금융아이콘_PNG_수호천사동양생명.png",
  // "KTB투자증권": "asset/img/bank/금융아이콘_PNG_KTB투자증권.png",
  // "현대차증권": "asset/img/bank/금융아이콘_PNG_현대차증권.png",
  // "SBI": "asset/img/bank/금융아이콘_PNG_SBI.png",
  // "AIG": "asset/img/bank/금융아이콘_PNG_AIG.png",
  // "유진": "asset/img/bank/금융아이콘_PNG_유진.png",
  // "RGA": "asset/img/bank/금융아이콘_PNG_RGA.png",
  // "AIA": "asset/img/bank/금융아이콘_PNG_AIA.png",
};